/* !---- DO NOT EDIT: This file autogenerated by com/jogamp/gluegen/JavaEmitter.java on Sat Oct 10 04:57:43 CEST 2015 ----! */

package com.jogamp.opencl.llb;

import com.jogamp.gluegen.runtime.*;
import com.jogamp.common.os.*;
import com.jogamp.common.nio.*;
import java.nio.*;

 /**
  * Java bindings to OpenCL, the Open Computing Language.
  * @author Michael Bien, GlueGen, et al.
  */
public interface CL extends CLContextBinding, CLProgramBinding, CLKernelBinding, CLCommandQueueBinding, CLDeviceBinding, CLImageBinding, CLBufferBinding, CLSamplerBinding, CLEventBinding, CLPlatformBinding{

  /** Defined as part of enum type "khronos_boolean_enum_t" - CType: int */
  public static final int KHRONOS_FALSE = 0x0;
  /** Defined as part of enum type "khronos_boolean_enum_t" - CType: int */
  public static final int KHRONOS_TRUE = 0x1;
  /** Defined as part of enum type "khronos_boolean_enum_t" - CType: int */
  public static final int KHRONOS_BOOLEAN_ENUM_FORCE_SIZE = 0x7fffffff;
  /** CType: int */
  public static final int CL_INVALID_WORK_ITEM_SIZE = -55;
  /** CType: int */
  public static final int CL_INVALID_GLOBAL_WORK_SIZE = -63;
  /** CType: int */
  public static final int CL_DBL_MAX_10_EXP = 0x134;
  /** CType: int */
  public static final int CL_FLT_MIN_EXP = -125;
  /** CType: float */
  public static final float CL_M_2_SQRTPI_F = 1.1283792257309f;
  /** CType: int */
  public static final int CL_PROFILING_INFO_NOT_AVAILABLE = -7;
  /** CType: int */
  public static final int CL_INVALID_KERNEL_ARGS = -52;
  /** CType: int */
  public static final int cl_ext_migrate_memobject = 0x1;
  /** CType: int */
  public static final int CL_AFFINITY_DOMAIN_NUMA_EXT = 0x10;
  /** CType: int */
  public static final int CL_INVALID_PARTITION_NAME_EXT = -1059;
  /** CType: int */
  public static final int CL_DBL_DIG = 0xf;
  /** CType: int */
  public static final int CL_INVALID_MIP_LEVEL = -62;
  /** CType: int */
  public static final int CL_DBL_RADIX = 0x2;
  /** CType: int */
  public static final int CL_INVALID_ARG_INDEX = -49;
  /** CType: float */
  public static final float CL_M_2_PI = 0.6366197723675814f;
  /** CType: int */
  public static final int CL_OUT_OF_RESOURCES = -5;
  /** CType: int */
  public static final int CL_VERSION_1_1 = 0x1;
  /** CType: int */
  public static final int CL_VERSION_1_0 = 0x1;
  /** CType: int */
  public static final int CL_INVALID_PLATFORM = -32;
  /** CType: float */
  public static final float CL_M_PI_2_F = 1.57079637050629f;
  /** CType: int */
  public static final int CL_RUNNING = 0x1;
  /** CType: int */
  public static final int CL_INVALID_KERNEL = -48;
  /** CType: int */
  public static final int CL_CHAR_MAX = 0x7f;
  /** CType: float */
  public static final float CL_M_LN10_F = 2.30258512496948f;
  /** CType: int */
  public static final int CL_SCHAR_MAX = 0x7f;
  /** CType: int */
  public static final int GLEXT_64_TYPES_DEFINED = 0x1;
  /** CType: int */
  public static final int CL_CHAR_BIT = 0x8;
  /** CType: int */
  public static final int CL_DBL_MIN_10_EXP = -307;
  /** CType: float */
  public static final float CL_M_1_PI = 0.3183098861837907f;
  /** CType: int */
  public static final int CL_INVALID_PROGRAM_EXECUTABLE = -45;
  /** CType: int */
  public static final int KHRONOS_MAX_ENUM = 0x7fffffff;
  /** CType: float */
  public static final float CL_MAXFLOAT = 3.4028234663852886E38f;
  /** CType: int */
  public static final int CL_TRUE = 0x1;
  /** CType: float */
  public static final float CL_FLT_EPSILON = 1.1920928955078125E-7f;
  /** CType: int */
  public static final int CL_AFFINITY_DOMAIN_L3_CACHE_EXT = 0x3;
  /** CType: double */
  public static final double CL_DBL_MAX = 1.7976931348623157E308;
  /** CType: int */
  public static final int CL_SUBMITTED = 0x2;
  /** CType: float */
  public static final float CL_M_PI_4_F = 0.78539818525314f;
  /** CType: int */
  public static final int CL_EXEC_STATUS_ERROR_FOR_EVENTS_IN_WAIT_LIST = -14;
  /** CType: int */
  public static final int KHRONOS_SUPPORT_FLOAT = 0x1;
  /** CType: int */
  public static final int CL_INVALID_SAMPLER = -41;
  /** CType: float */
  public static final float CL_M_SQRT2_F = 1.41421353816986f;
  /** CType: int */
  public static final int CL_FLT_MIN_10_EXP = -37;
  /** CType: int */
  public static final int CL_INVALID_CONTEXT = -34;
  /** CType: float */
  public static final float CL_M_E = 2.718281828459045f;
  /** CType: int */
  public static final int CL_EXEC_KERNEL = ( 0x1 << 0x0 );
  /** CType: int */
  public static final int CL_INT_MAX = 0x7fffffff;
  /** CType: float */
  public static final float CL_FLT_MIN = 1.1754943508222875E-38f;
  /** CType: int */
  public static final int CL_DBL_MAX_EXP = 0x400;
  /** CType: int */
  public static final int CL_AFFINITY_DOMAIN_L4_CACHE_EXT = 0x4;
  /** CType: float */
  public static final float CL_M_SQRT1_2 = 0.7071067811865476f;
  /** CType: int */
  public static final int CL_INVALID_PARTITION_COUNT_EXT = -1058;
  /** CType: int */
  public static final int CL_INVALID_ARG_VALUE = -50;
  /** CType: int */
  public static final int CL_INVALID_DEVICE_TYPE = -31;
  /** CType: int */
  public static final int CL_SUCCESS = 0x0;
  /** CType: int */
  public static final int CL_INVALID_BUILD_OPTIONS = -43;
  /** CType: float */
  public static final float CL_M_LN2_F = 0.6931471824646f;
  /** CType: int */
  public static final int CL_INVALID_VALUE = -30;
  /** CType: int */
  public static final int CL_COMPLETE = 0x0;
  /** CType: int */
  public static final int cl_khr_icd = 0x1;
  /** CType: int */
  public static final int CL_INVALID_BUFFER_SIZE = -61;
  /** CType: int */
  public static final int CL_FLT_MAX_EXP = 0x80;
  /** CType: int */
  public static final int CL_COMPILER_NOT_AVAILABLE = -3;
  /** CType: int */
  public static final int CL_INVALID_EVENT = -58;
  /** CType: int */
  public static final int CL_SHRT_MAX = 0x7fff;
  /** CType: int */
  public static final int CL_EGL_DISPLAY_KHR = 0x2009;
  /** CType: float */
  public static final float CL_M_2_SQRTPI = 1.1283791670955126f;
  /** CType: int */
  public static final int CL_INVALID_WORK_GROUP_SIZE = -54;
  /** CType: float */
  public static final float CL_M_PI = 3.141592653589793f;
  /** CType: int */
  public static final int CL_FLT_MANT_DIG = 0x18;
  /** CType: double */
  public static final double CL_DBL_MIN = 2.2250738585072014E-308;
  /** CType: int */
  public static final int cl_khr_gl_sharing = 0x1;
  /** CType: int */
  public static final int CL_NONE = 0x0;
  /** CType: int */
  public static final int CL_FLT_RADIX = 0x2;
  /** CType: float */
  public static final float CL_M_1_PI_F = 0.31830987334251f;
  /** CType: int */
  public static final int CL_CGL_SHAREGROUP_KHR = 0x200c;
  /** CType: int */
  public static final int CL_INVALID_KERNEL_NAME = -46;
  /** CType: float */
  public static final float CL_M_PI_F = 3.14159274101257f;
  /** CType: float */
  public static final float CL_M_PI_4 = 0.7853981633974483f;
  /** CType: float */
  public static final float CL_M_PI_2 = 1.5707963267948966f;
  /** CType: float */
  public static final float CL_M_E_F = 2.71828174591064f;
  /** CType: float */
  public static final float CL_M_SQRT1_2_F = 0.70710676908493f;
  /** CType: int */
  public static final int CL_AFFINITY_DOMAIN_NEXT_FISSIONABLE_EXT = 0x100;
  /** CType: int */
  public static final int CL_DBL_MIN_EXP = -1021;
  /** CType: float */
  public static final float CL_M_LN2 = 0.6931471805599453f;
  /** CType: float */
  public static final float CL_DBL_EPSILON = 2.220446049250313E-16f;
  /** CType: int */
  public static final int CL_INVALID_COMMAND_QUEUE = -36;
  /** CType: float */
  public static final float CL_FLT_MAX = 3.4028234663852886E38f;
  /** CType: int */
  public static final int CL_UCHAR_MAX = 0xff;
  /** CType: int */
  public static final int CL_GLX_DISPLAY_KHR = 0x200a;
  /** CType: int */
  public static final int CL_INVALID_BINARY = -42;
  /** CType: int */
  public static final int CL_INVALID_ARG_SIZE = -51;
  /** CType: int */
  public static final int CL_FLT_DIG = 0x6;
  /** CType: float */
  public static final float CL_M_LN10 = 2.302585092994046f;
  /** CType: int */
  public static final int CL_INVALID_EVENT_WAIT_LIST = -57;
  /** CType: int */
  public static final int CL_BUFFER_CREATE_TYPE_REGION = 0x1220;
  /** CType: float */
  public static final float CL_M_LOG2E_F = 1.44269502162933f;
  /** CType: float */
  public static final float CL_M_LOG10E = 0.4342944819032518f;
  /** CType: int */
  public static final int CL_INVALID_PROGRAM = -44;
  /** CType: int */
  public static final int CL_INVALID_IMAGE_SIZE = -40;
  /** CType: int */
  public static final int CL_INVALID_HOST_PTR = -37;
  /** CType: float */
  public static final float CL_M_SQRT2 = 1.4142135623730951f;
  /** CType: int */
  public static final int CL_WGL_HDC_KHR = 0x200b;
  /** CType: int */
  public static final int CL_INVALID_DEVICE = -33;
  /** CType: int */
  public static final int CL_INVALID_WORK_DIMENSION = -53;
  /** CType: int */
  public static final int CL_AFFINITY_DOMAIN_L2_CACHE_EXT = 0x2;
  /** CType: int */
  public static final int CL_INVALID_PROPERTY = -64;
  /** CType: int */
  public static final int CL_QUEUED = 0x3;
  /** CType: int */
  public static final int CL_INVALID_OPERATION = -59;
  /** CType: int */
  public static final int KHRONOS_SUPPORT_INT64 = 0x1;
  /** CType: int */
  public static final int CL_INVALID_KERNEL_DEFINITION = -47;
  /** CType: float */
  public static final float CL_M_2_PI_F = 0.63661974668503f;
  /** CType: int */
  public static final int CL_INVALID_GLOBAL_OFFSET = -56;
  /** CType: int */
  public static final int CL_AFFINITY_DOMAIN_L1_CACHE_EXT = 0x1;
  /** CType: int */
  public static final int CL_MISALIGNED_SUB_BUFFER_OFFSET = -13;
  /** CType: int */
  public static final int CL_USHRT_MAX = 0xffff;
  /** CType: int */
  public static final int CL_INVALID_IMAGE_FORMAT_DESCRIPTOR = -39;
  /** CType: int */
  public static final int cl_ext_device_fission = 0x1;
  /** CType: int */
  public static final int CL_INVALID_QUEUE_PROPERTIES = -35;
  /** CType: int */
  public static final int CL_DRIVER_VERSION = 0x102d;
  /** CType: int */
  public static final int HAS_STDDEF = 0x1;
  /** CType: int */
  public static final int CL_FLT_MAX_10_EXP = 0x26;
  /** CType: int */
  public static final int CL_MIGRATE_MEM_OBJECT_HOST_EXT = 0x1;
  /** CType: float */
  public static final float CL_M_LOG10E_F = 0.4342944920063f;
  /** CType: int */
  public static final int CL_EXEC_NATIVE_KERNEL = ( 0x1 << 0x1 );
  /** CType: int */
  public static final int CL_OUT_OF_HOST_MEMORY = -6;
  /** CType: float */
  public static final float CL_M_LOG2E = 1.4426950408889634f;
  /** CType: int */
  public static final int CL_INVALID_MEM_OBJECT = -38;
  /** CType: int */
  public static final int CL_FALSE = 0x0;
  /** CType: int */
  public static final int CL_DBL_MANT_DIG = 0x35;

  /** Interface to C language function: <br> <code>cl_int {@native clUnloadCompiler}(void)</code><br>   */
  public int clUnloadCompiler();


} // end of class CL
