/* !---- DO NOT EDIT: This file autogenerated by com/jogamp/gluegen/JavaEmitter.java on Sat Oct 10 04:57:09 CEST 2015 ----! */

package com.jogamp.opencl.llb;

import com.jogamp.gluegen.runtime.*;
import com.jogamp.common.os.*;
import com.jogamp.common.nio.*;
import java.nio.*;

 /**
  * Java bindings to OpenCL buffers.
  * @author Michael Bien, GlueGen, et al.
  */
public interface CLBufferBinding extends CLMemObjBinding{


  /** Interface to C language function: <br> <code>cl_mem {@native clCreateBuffer}(cl_context context, cl_mem_flags flags, size_t size, void *  host_ptr, cl_int *  errcode_ret)</code><br>
      @param host_ptr a direct or array-backed {@link java.nio.Buffer}
      @param errcode_ret a direct or array-backed {@link java.nio.IntBuffer}   */
  public long clCreateBuffer(long context, long flags, long size, Buffer host_ptr, IntBuffer errcode_ret);

  /** Interface to C language function: <br> <code>cl_mem {@native clCreateBuffer}(cl_context context, cl_mem_flags flags, size_t size, void *  host_ptr, cl_int *  errcode_ret)</code><br>
      @param host_ptr a direct or array-backed {@link java.nio.Buffer}   */
  public long clCreateBuffer(long context, long flags, long size, Buffer host_ptr, int[] errcode_ret, int errcode_ret_offset);

  /** Interface to C language function: <br> <code>cl_mem {@native clCreateSubBuffer}(cl_mem buffer, cl_mem_flags flags, cl_buffer_create_type buffer_create_type, const void *  buffer_create_info, cl_int *  errcode_ret)</code><br>
      @param buffer_create_info a direct or array-backed {@link java.nio.Buffer}
      @param errcode_ret a direct or array-backed {@link java.nio.IntBuffer}   */
  public long clCreateSubBuffer(long buffer, long flags, int buffer_create_type, Buffer buffer_create_info, IntBuffer errcode_ret);

  /** Interface to C language function: <br> <code>cl_mem {@native clCreateSubBuffer}(cl_mem buffer, cl_mem_flags flags, cl_buffer_create_type buffer_create_type, const void *  buffer_create_info, cl_int *  errcode_ret)</code><br>
      @param buffer_create_info a direct or array-backed {@link java.nio.Buffer}   */
  public long clCreateSubBuffer(long buffer, long flags, int buffer_create_type, Buffer buffer_create_info, int[] errcode_ret, int errcode_ret_offset);


} // end of class CLBufferBinding
